/*
---------------------------------------------------------------------------------------------------------------
* @author       Animesh Kumar Verma
---------------------------------------
* @description  Controller class for Contact which performs the below actions. 
*               -Controlls the infinite loop of user creation
*    -----------------------------------------------------------------------------------------------------------
*/


Global Class CreateUserOnContactHandlerBoolen{

    global Static Boolean updateUserFlag = true;
    global Static Boolean contactFlag = true;
}