@isTest
private class MatterCommentsTest {
/*    
    private static ApexPages.StandardController stdCtrl;
    private static matterCommentsController ctrl;
    private static Matter__c matterRec;
    private static Case__c caseRec;
    
    private static testMethod void testMatterComments() {
        caseRec = new Case__c();
        insert caseRec;
        RecordType hrRecType = [Select Id From RecordType  Where SobjectType = 'Matter__c' and DeveloperName = 'Internal_Referral'];
        matterRec = new Matter__c(RecordType=hrRecType, Case__c=caseRec.Id);
        insert matterRec;
        PageReference pageRef = Page.MatterComments;
        Test.setCurrentPage(pageRef);
        stdCtrl = new ApexPages.StandardController(matterRec);
        ctrl = new matterCommentsController(stdCtrl);
        ctrl.matter.New_Notes__c = 'Test';
        ctrl.saveRecord();
    }
*/
}